"use client";
import {useState} from 'react';import {CalendarDays,ChevronDown,Wallet} from 'lucide-react';import {recurringForecast} from '@/lib/recurring-forecast';import {formatMoney} from '@/lib/currency';import {statsDateLabel} from '@/lib/stats-date-range';
type Props={payments:Parameters<typeof recurringForecast>[0];sources:Parameters<typeof recurringForecast>[1];currency:string;today:string};
export function FundingForecast(props:Props){const [days,setDays]=useState(30);const f=recurringForecast(props.payments,props.sources,props.currency,props.today,days);const money=(n:number)=>formatMoney(n,props.currency);
 return <details className="group rounded-xl border border-indigo-500/25 bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-2 rounded-xl bg-indigo-500/5 px-4 py-3 text-sm font-medium text-indigo-800 dark:text-indigo-300 [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><Wallet className="h-4 w-4 text-indigo-600 dark:text-indigo-400"/>Account funding forecast</span><span className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{f.invalid.length?'Needs review':f.banks.some(s=>s.needed>0)?`${money(f.banks.reduce((sum,s)=>sum+s.needed,0))} needed`:`Next ${days} days`}</span><ChevronDown className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180"/></span></summary><div className="space-y-3 border-t p-3"><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-xs">Look ahead<select className="h-10 rounded-md border bg-background px-2 text-sm" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={14}>14 days</option><option value={30}>30 days</option><option value={60}>60 days</option></select></label><p className="text-xs text-muted-foreground">Through {statsDateLabel(f.end)} · {props.currency}</p></div><p className="text-xs text-muted-foreground">Uses current balances and unrecorded scheduled bank charges, including overdue items. Expected income, unscheduled spending, transfers, and manual credit-card repayments are not included. This is a forecast; it does not create transactions.</p>
 {f.invalid.length>0&&<p role="alert" className="text-xs text-amber-700 dark:text-amber-400">Forecast is incomplete. Check the dates and payment sources for: {f.invalid.join(', ')}.</p>}
 <div className="grid gap-3 md:grid-cols-2">{f.banks.map(s=><div key={s.id} className={`min-w-0 rounded-lg border p-3 ${s.needed>0?'border-amber-500/30 bg-amber-500/5':'border-teal-500/20'}`}><h2 className="text-sm font-semibold">{s.name}</h2><dl className="mt-2 grid grid-cols-2 gap-2 text-xs">{[['Current balance',s.balance],['Scheduled bank charges',s.total],['Projected balance',s.projected],['Funding needed',s.needed]].map(([label,amount])=><div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 break-words font-semibold tabular-nums">{money(Number(amount))}</dd></div>)}</dl><p className={`mt-2 text-xs font-medium ${s.firstShortfall?'text-amber-700 dark:text-amber-400':'text-teal-700 dark:text-teal-400'}`}>{s.firstShortfall?`${s.firstShortfall<props.today?'Overdue bills need funding now':'First shortfall: '+statsDateLabel(s.firstShortfall)}`:'Current balance covers these scheduled charges'}</p><details className="mt-3 border-t pt-2"><summary className="cursor-pointer text-xs font-medium">Payment timeline · {s.entries.length} charges</summary><div className="mt-2 space-y-2">{s.entries.slice(0,15).map((e,i)=><div key={`${e.id}:${e.date}:${i}`} className="border-b pb-2 text-xs last:border-b-0"><div className="flex flex-wrap justify-between gap-1"><span className="flex items-center gap-1 text-muted-foreground"><CalendarDays className="h-3 w-3"/>{statsDateLabel(e.date)}{e.overdue?' · overdue':''}</span><strong>{money(e.amount)}</strong></div><p className="mt-1 break-words">{e.name}</p><p className="mt-1 text-muted-foreground">Balance after charge: <span className={e.projected<0?'text-red-600 dark:text-red-400':''}>{money(e.projected)}</span></p></div>)}{s.entries.length>15&&<p className="text-muted-foreground">Showing the first 15 charges. Totals include all {s.entries.length} charges; review overdue schedules before recording.</p>}</div></details></div>)}</div>
 {!f.banks.length&&<p className="text-sm text-muted-foreground">No scheduled bank charges within this period.</p>}
 {f.cardCharges>0&&<p className="rounded-lg bg-muted/40 p-2 text-xs">Scheduled credit-card purchases: <strong>{money(f.cardCharges)}</strong>. These increase card debt and are excluded from bank funding needs. Card repayments remain manual.</p>}
 </div></details>;
}
