import { test } from 'node:test';
import assert from 'node:assert/strict';
import { albertaDate, nextOccurrence, validDate } from '../src/lib/recurring-calendar';
import { transactionEffects } from '../src/lib/transaction-effects';
import { runRecurring } from '../src/lib/recurring-runner';
test('Alberta calendar dates and valid dates',()=>{assert.equal(albertaDate(new Date('2026-10-04T01:00Z')),'2026-10-03');assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2028-02-29'),true);});
test('Monthly anchors recover after short months and leap years',()=>{assert.equal(nextOccurrence('2026-01-31','2026-01-31','MONTHLY'),'2026-02-28');assert.equal(nextOccurrence('2026-02-28','2026-01-31','MONTHLY'),'2026-03-31');assert.equal(nextOccurrence('2028-02-29','2028-02-29','YEARLY'),'2029-02-28');assert.equal(nextOccurrence('2031-02-28','2028-02-29','YEARLY'),'2032-02-29');assert.equal(nextOccurrence('2026-12-30','2026-12-30','WEEKLY'),'2027-01-06');});
test('Wise transfer reversal uses actual received amount; same currency is unchanged',()=>{const t={type:'TRANSFER',amount:150,toAmount:108,accountId:'CAD',toAccountId:'USD'};assert.deepEqual(transactionEffects(t),[{model:'account',id:'CAD',amount:-150},{model:'account',id:'USD',amount:108}]);assert.deepEqual(transactionEffects(t,-1),[{model:'account',id:'CAD',amount:150},{model:'account',id:'USD',amount:-108}]);assert.equal(transactionEffects({...t,toAmount:null})[1].amount,150);});
function fixture(card=false,invalidOwner=false,failBalance=false){
 const today=albertaDate();let state={payment:{id:'r',userId:'owner',active:true,nextDate:today,anchorDate:today,frequency:'MONTHLY',sourceId:card?'card:c':'bank',currency:'CAD',categoryId:'cat',name:'Bill',amount:25},entries:[] as any[],occurrences:[] as any[],bank:100,debt:50};
 const tx:any={recurringPayment:{findFirst:async()=>({...state.payment}),update:async({data}:any)=>{Object.assign(state.payment,data);}},category:{findFirst:async({where}:any)=>where.userId==='owner'?{}:null},debt:{findFirst:async({where}:any)=>where.userId==='owner'&&!invalidOwner?{currency:'CAD'}:null,update:async({data}:any)=>{if(failBalance)throw Error('fault');state.debt+=Number(data.currentBalance.increment);}},financialAccount:{findFirst:async({where}:any)=>where.userId==='owner'&&!invalidOwner?{currency:'CAD'}:null,update:async({data}:any)=>{if(failBalance)throw Error('fault');state.bank-=Number(data.balance.decrement);}},transaction:{create:async({data}:any)=>{const p={...data,id:'tx'};state.entries.push(p);return p;}},recurringOccurrence:{findUnique:async({where}:any)=>state.occurrences.find(x=>x.scheduledDate===where.recurringId_scheduledDate.scheduledDate)||null,create:async({data}:any)=>{state.occurrences.push(data);}}};
 const db:any={recurringPayment:{findMany:async({where}:any)=>state.payment.nextDate<=where.nextDate.lte?[{...state.payment}]:[]},$transaction:async(fn:any)=>{const before=structuredClone(state);try{return await fn(tx);}catch(e){state=before;throw e;}}};return {db,state:()=>state,today};
}
test('Runner records bank and card expenses once and never replays deleted entries',async()=>{for(const card of [false,true]){const f=fixture(card);assert.equal((await runRecurring(f.db,'owner')).created,1);assert.equal(f.state().entries[0].type,'EXPENSE');assert.equal(f.state().bank,card?100:75);assert.equal(f.state().debt,card?75:50);await runRecurring(f.db,'owner');assert.equal(f.state().entries.length,1);f.state().entries=[];f.state().payment.nextDate=f.today;await runRecurring(f.db,'owner');assert.equal(f.state().entries.length,0);assert.equal(f.state().bank,card?100:75);}});
test('Invalid owner reference or balance failure leaves entries, balance and schedule unchanged',async()=>{for(const f of [fixture(false,true),fixture(false,false,true)]){const result=await runRecurring(f.db,'owner');assert.equal(result.failures.length,1);assert.equal(f.state().entries.length,0);assert.equal(f.state().occurrences.length,0);assert.equal(f.state().bank,100);assert.equal(f.state().payment.nextDate,f.today);}});
