"use client";
import { useLanguage } from "@/components/language-provider";

import { I18nText } from "@/components/language-provider";
import {useEffect,useState} from 'react';import {CalendarDays,Pencil} from 'lucide-react';import {getIncomePlan,saveIncomePlan,removeIncomePlan} from '@/lib/actions/income-plan-actions';import {incomePlanFigures} from '@/lib/income-plan';import {formatMoney} from '@/lib/currency';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import { localizedToast as toast } from "@/lib/i18n/client-messages";
export function IncomePlan({month,currency,received,budgeted,loadingBudget}:{month:string;currency:string;received:number;budgeted:number;loadingBudget:boolean}){
 const { t: ppT } = useLanguage();

 const [expected,setExpected]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState(false),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setEdit(false);setError('');setExpected(null);getIncomePlan(month,currency).then(r=>{if(active){setExpected(r.amount);setError(r.error||'');}}).catch(()=>{if(active)setError('Unable to load income plan.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month,currency,version]);
 const f=incomePlanFigures(expected,received,budgeted),money=(n:number|null)=>n===null?'Not set':formatMoney(n,currency),waiting=loading||loadingBudget;
 async function save(){setBusy(true);try{const r=await saveIncomePlan(month,currency,value);if(!r.success){toast.error(r.error);return;}setEdit(false);setVersion(v=>v+1);toast.success('Expected income saved. Account balances are unchanged.');}catch{toast.error('Unable to save income plan.');}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{const r=await removeIncomePlan(month,currency);if(!r.success){toast.error(r.error);return;}setEdit(false);setVersion(v=>v+1);toast.success('Income plan removed. Transactions are unchanged.');}catch{toast.error('Unable to remove the income plan.');}finally{setBusy(false);}}
 return <section aria-label={ppT("Monthly income plan")} className="rounded-xl border border-indigo-500/25 bg-indigo-500/5 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-sm font-semibold text-indigo-800 dark:text-indigo-300"><CalendarDays className="h-4 w-4 text-indigo-600 dark:text-indigo-400"/>{""}<I18nText text={"Income plan ·"}/>{" "}{month} · {currency}</h2><Button type="button" variant="outline" size="sm" className="border-indigo-500/25 text-indigo-800 hover:bg-indigo-500/10 dark:text-indigo-300" disabled={loading||busy||!!error} onClick={()=>{setValue(expected===null?'':expected.toFixed(2));setEdit(true);}}><Pencil className="h-3 w-3"/><I18nText text={expected===null?'Set expected income':'Edit plan'}/></Button></div>
 {error?<p role="alert" className="mt-2 text-xs text-amber-700 dark:text-amber-400"><I18nText text={error}/><Button variant="link" size="sm" onClick={()=>setVersion(v=>v+1)}>{""}<I18nText text={"Retry"}/>{""}</Button></p>:<><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'Expected income',amount:expected},{label:'Received income',amount:received},{label:'Still expected',amount:f.stillExpected},{label:'Planned left to budget',amount:f.plannedLeftToBudget}].map(r=><div key={r.label} className="min-w-0"><p className="text-xs text-muted-foreground"><I18nText text={r.label}/></p><p className="mt-1 break-words text-base font-semibold tabular-nums">{waiting?'…':money(r.amount)}</p></div>)}</div><p className="mt-2 text-xs text-muted-foreground">{""}<I18nText text={"Expected income is a planning total, not money in your accounts. “Left to Budget” below still uses received income."}/>{""}{!waiting&&f.abovePlan&&f.abovePlan>0?` Received ${money(f.abovePlan)} above the plan.`:''}</p>
 {edit&&<form className="mt-3 space-y-2 border-t pt-3" onSubmit={e=>{e.preventDefault();void save();}}><label className="block text-xs font-medium">{""}<I18nText text={"Expected income for this month ("}/>{""}{currency})<Input className="mt-1 max-w-xs" value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" placeholder={ppT("0.00")} required disabled={busy}/></label><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy} type="submit"><I18nText text={busy?'Saving…':'Save plan'}/></Button><Button size="sm" type="button" variant="outline" disabled={busy} onClick={()=>setEdit(false)}>{""}<I18nText text={"Cancel"}/>{""}</Button>{expected!==null&&<Button size="sm" type="button" variant="ghost" disabled={busy} onClick={()=>void remove()}>{""}<I18nText text={"Remove plan"}/>{""}</Button>}</div></form>}</>}
 </section>;
}
