"use client";
import { useEffect, useState } from "react";
import { Home, Plus, Pencil, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getProperties, saveProperty, deleteProperty } from "@/lib/actions/property-actions";

type Property={id:string;name:string;currency:string;estimatedValue:number;mortgageDebtId:string|null;mortgageBalance:number};
type Mortgage={id:string;name:string;currency:string;balance:number};
const format=(v:number,c:string)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:c,currencyDisplay:"code"}).format(v);
export function PropertySection(){
 const [rows,setRows]=useState<Property[]>([]),[mortgages,setMortgages]=useState<Mortgage[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<Property|null|undefined>(undefined),[currency,setCurrency]=useState("USD"),[mortgage,setMortgage]=useState(""),[value,setValue]=useState(""),[balance,setBalance]=useState("");
 async function load(){const r=await getProperties();if(r.success){setRows(r.data);setMortgages(r.mortgages);}else setError(r.error);setLoading(false);}
 useEffect(()=>{void load();},[]);
 function open(row:Property|null){setEditing(row);setCurrency(row?.currency??"USD");setMortgage(row?.mortgageDebtId??"");setValue(row?String(row.estimatedValue):"");setBalance("");setError("");}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);form.set("currency",currency);form.set("mortgageDebtId",mortgage);form.set("mortgageBalance",balance||"0");const r=await saveProperty(editing?.id??null,form);if(r.success){setEditing(undefined);await load();}else setError(r.error);setBusy(false);}
 async function remove(row:Property){if(!window.confirm("Remove this property from net worth? Its linked mortgage stays in Debts until you update or remove it there."))return;setBusy(true);const r=await deleteProperty(row.id);if(r.success)await load();else setError(r.error);setBusy(false);}
 const linked=mortgages.find(m=>m.id===mortgage);
 return <section className="mb-6 rounded-2xl border border-teal-500/25 bg-teal-500/[0.03] p-4 sm:p-5" aria-label="Property">
 <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-500/10 p-2 text-teal-600 dark:text-teal-400"><Home className="h-5 w-5"/></span><div><h2 className="text-lg font-semibold">Property</h2><p className="text-xs text-muted-foreground">Included in net worth, separate from account balances.</p></div></div><Button size="sm" variant="outline" onClick={()=>open(null)} disabled={busy}><Plus className="mr-1 h-4 w-4"/>Add property</Button></div>
 {error&&<p role="alert" className="mt-3 text-sm text-red-600 dark:text-red-400">{error}</p>}
 {editing!==undefined&&<form onSubmit={submit} className="mt-4 rounded-xl border bg-background p-4 space-y-4">
 <div className="flex items-center justify-between"><h3 className="font-semibold">{editing?"Edit property":"New property"}</h3><Button type="button" variant="ghost" size="sm" disabled={busy} aria-label="Close property form" onClick={()=>setEditing(undefined)}><X className="h-4 w-4"/></Button></div>
 <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Property name<Input className="mt-1" name="name" required maxLength={100} defaultValue={editing?.name??""} placeholder="My house" key={editing?.id??"new"}/></label>
 <label className="text-sm font-medium">Currency<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={currency} disabled={Boolean(editing)||busy} onChange={e=>{setCurrency(e.target.value);setMortgage("");}}><option value="USD">USD</option><option value="CAD">CAD</option></select></label>
 <label className="text-sm font-medium">Estimated current value<Input className="mt-1" name="estimatedValue" inputMode="decimal" required value={value} onChange={e=>setValue(e.target.value)} placeholder="0.00"/><span className="text-xs text-muted-foreground font-normal">Use the full property value, before subtracting the mortgage.</span></label>
 {!editing&&<label className="text-sm font-medium">Mortgage<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={mortgage} onChange={e=>setMortgage(e.target.value)}><option value="">No existing mortgage / create new</option>{mortgages.filter(m=>m.currency===currency&&!rows.some(r=>r.mortgageDebtId===m.id)).map(m=><option key={m.id} value={m.id}>{m.name} · {format(m.balance,m.currency)}</option>)}</select></label>}
 {editing?.mortgageDebtId?<div className="text-sm"><p className="font-medium">Linked mortgage balance</p><p className="mt-2">{format(editing.mortgageBalance,currency)}</p><p className="text-xs text-muted-foreground">Manage corrections and payments in Debts. This save only updates the property value.</p></div>:!mortgage&&<label className="text-sm font-medium">Remaining mortgage principal<Input className="mt-1" inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="0.00"/><span className="text-xs text-muted-foreground font-normal">Leave blank if paid off. A positive amount creates one linked mortgage in Debts.</span></label>}
 </div>
 {!editing&&linked&&<p className="text-xs text-muted-foreground">Uses your existing mortgage. No duplicate loan will be created.</p>}
 <p className="text-xs text-muted-foreground">Equity is property value minus the linked mortgage. If you already track this house as an Other account, remove that duplicate before adding it here.</p>
 <div className="flex gap-2"><Button disabled={busy} type="submit">{busy?"Saving…":"Save property"}</Button><Button disabled={busy} variant="outline" type="button" onClick={()=>setEditing(undefined)}>Cancel</Button></div>
 </form>}
 {loading?<p className="mt-4 text-sm text-muted-foreground">Loading properties…</p>:rows.length===0?<p className="mt-4 text-sm text-muted-foreground">Track your home value and mortgage equity here.</p>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{rows.map(row=>{const equity=row.estimatedValue-row.mortgageBalance;return <article key={row.id} className="rounded-xl border bg-background p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-base">{row.name}</h3><span className="text-xs text-muted-foreground">{row.currency}</span></div><div className="flex gap-1"><Button aria-label={`Edit ${row.name}`} size="sm" variant="outline" disabled={busy} onClick={()=>open(row)}><Pencil className="h-3 w-3 mr-1"/>Edit</Button><Button aria-label={`Remove ${row.name}`} size="sm" variant="ghost" disabled={busy} onClick={()=>remove(row)}><Trash2 className="h-4 w-4"/></Button></div></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-muted-foreground">Property value</p><p className="font-semibold">{format(row.estimatedValue,row.currency)}</p></div><div><p className="text-muted-foreground">Mortgage</p><p className="font-semibold">{format(row.mortgageBalance,row.currency)}</p></div></div><div className="mt-3 border-t pt-3 flex items-center justify-between gap-2"><span className="text-sm font-medium">Equity</span><strong className={equity<0?"text-red-600 dark:text-red-400":"text-teal-700 dark:text-teal-400"}>{format(equity,row.currency)}</strong></div></article>})}</div>}
 </section>;
}
