"use client";
import { useEffect,useState } from 'react';
import { LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine } from 'recharts';
import { ChevronDown,History,Plus,Pencil } from 'lucide-react';
import { getNetWorthHistory,saveNetWorthHistory,useAutomaticNetWorth } from '@/lib/actions/net-worth-history-actions';
import { chartTooltipStyle,compactChartAmount,CHART_COLORS } from '@/components/charts/financial-charts';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { formatMoney } from '@/lib/currency';
import { albertaDate } from '@/lib/recurring-calendar';
import { toast } from 'sonner';
type Row={id:string;month:string;assets:number;liabilities:number;netWorth:number;source:string;capturedAt:string};
const label=(month:string)=>new Intl.DateTimeFormat('en-CA',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${month}-01T12:00:00Z`));
export function NetWorthHistory({currency,month}:{currency:string;month:string}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[open,setOpen]=useState(false),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState(false);
 const todayMonth=albertaDate().slice(0,7),through=month>todayMonth?todayMonth:month;
 useEffect(()=>{let active=true;setLoading(true);setRows([]);setError('');getNetWorthHistory(currency,through).then(r=>{if(active){setRows(r.rows);setError(r.error||'');}}).catch(()=>{if(active)setError('Unable to load history. Please retry.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[currency,through,revision]);
 const latest=rows.at(-1),previous=rows.at(-2),difference=latest&&previous?Math.round((latest.netWorth-previous.netWorth)*100)/100:null;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);form.set('currency',currency);setBusy(true);try{const r=await saveNetWorthHistory(form);if(!r.success){toast.error(r.error);return;}setOpen(false);setRevision(v=>v+1);toast.success('Historical balance saved. Live account balances were not changed.');}catch{toast.error('Unable to save history.');}finally{setBusy(false);}}
 async function restore(){setBusy(true);try{const r=await useAutomaticNetWorth(currency);if(!r.success){toast.error(r.error);return;}setRevision(v=>v+1);toast.success('This month now follows live balances.');}catch{toast.error('Unable to update history.');}finally{setBusy(false);}}
 return <details className="group mt-3 rounded-xl border bg-card text-card-foreground">
  <summary className="flex cursor-pointer list-none items-center justify-between gap-3 rounded-xl px-4 py-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"><span className="flex min-w-0 items-center gap-2"><History aria-hidden className="h-4 w-4 shrink-0 text-teal-600"/><span className="font-medium">Net-worth history</span></span><span className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{loading?'Loading…':difference!==null?<span className={difference>=0?'text-emerald-600 dark:text-emerald-400':'text-red-600 dark:text-red-400'}>{difference>0?'+':''}{formatMoney(difference,currency)}</span>:latest?'Tracking started':'View history'}</span><ChevronDown aria-hidden className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180"/></span></summary>
  <div className="space-y-4 border-t p-4">
   <div className="flex flex-wrap items-start justify-between gap-3"><div className="text-xs text-muted-foreground"><p>Up to {label(through)} · {currency} only · latest 12 recorded months</p>{latest&&<p className="mt-1">Latest saved: {label(latest.month)}{previous?` · change compared with ${label(previous.month)}`:''}</p>}</div><Button type="button" size="sm" variant="outline" disabled={loading||!!error} onClick={()=>{setEditing(null);setOpen(true);}}><Plus className="h-4 w-4"/>Add month</Button></div>
   {error?<div role="alert" className="text-sm text-amber-700 dark:text-amber-400">{error}<Button type="button" variant="link" onClick={()=>setRevision(v=>v+1)}>Retry</Button></div>:loading?<p className="text-sm text-muted-foreground">Loading history…</p>:<>
    {rows.length>1?<ResponsiveContainer width="100%" height={200}><LineChart data={rows.map(r=>({...r,label:label(r.month)}))} margin={{top:12,right:12,left:0,bottom:0}}><CartesianGrid stroke="currentColor" opacity={0.1} vertical={false}/><XAxis dataKey="label" tick={{fill:'currentColor',fontSize:11}} tickLine={false} axisLine={false} minTickGap={20}/><YAxis width={50} tickFormatter={compactChartAmount} tick={{fill:'currentColor',fontSize:11}} tickLine={false} axisLine={false}/><ReferenceLine y={0} stroke="currentColor" strokeOpacity={0.2}/><Tooltip formatter={v=>formatMoney(Number(v),currency)} contentStyle={chartTooltipStyle}/><Line type="linear" dataKey="netWorth" name="Net worth" stroke={CHART_COLORS.net} strokeWidth={2} dot={{r:3}} isAnimationActive={false}/></LineChart></ResponsiveContainer>:<p className="text-sm text-muted-foreground">{rows.length?'Your first monthly balance is saved. Add an earlier month or return next month to see a trend.':'No recorded balances for this period. Add a historical month to start.'}</p>}
    <p className="text-xs text-muted-foreground">Automatic balances update when Dashboard opens. Past months retain their last recorded values; missing months are not estimated. Manual totals stay fixed until edited.</p>
    <div className="space-y-2">{[...rows].reverse().map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><div><span className="text-sm font-medium">{label(r.month)}</span><span className="ml-2 text-xs text-muted-foreground">{r.source==='MANUAL'?'Manual':r.month===todayMonth?'In progress':'Last recorded'}</span></div><Button type="button" size="sm" variant="outline" aria-label={`Edit ${label(r.month)} balance`} onClick={()=>{setEditing(r);setOpen(true);}}><Pencil className="h-3 w-3"/>Edit</Button></div><dl className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted-foreground">Assets</dt><dd className="font-medium">{formatMoney(r.assets,currency)}</dd></div><div><dt className="text-muted-foreground">Liabilities</dt><dd className="font-medium">{formatMoney(r.liabilities,currency)}</dd></div></dl><div className="mt-2 flex flex-wrap justify-between gap-1 text-sm"><span>Net worth</span><strong className={r.netWorth<0?'text-red-600 dark:text-red-400':'text-teal-700 dark:text-teal-400'}>{formatMoney(r.netWorth,currency)}</strong></div><p className="mt-1 text-xs text-muted-foreground">Recorded {new Intl.DateTimeFormat('en-CA',{dateStyle:'medium',timeZone:'America/Edmonton'}).format(new Date(r.capturedAt))}</p>{r.month===todayMonth&&r.source==='MANUAL'&&<Button type="button" variant="link" size="sm" disabled={busy} onClick={restore}>Use live balances for this month</Button>}</div>)}</div>
   </>}
  </div>
  <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="mx-0 w-[calc(100%-2rem)] max-w-md rounded-xl"><DialogHeader><DialogTitle>{editing?'Edit monthly balance':'Add historical balance'}</DialogTitle><DialogDescription>Enter totals in {currency}. This changes the history only, not accounts, debts, or transactions.</DialogDescription></DialogHeader><form key={editing?.id||'new'} onSubmit={save} className="space-y-4"><label className="block space-y-1 text-sm"><span>Month</span><Input type="month" name="month" min="1900-01" max={todayMonth} required defaultValue={editing?.month||through}/></label><label className="block space-y-1 text-sm"><span>Total assets ({currency})</span><Input name="assets" inputMode="decimal" required placeholder="0.00" defaultValue={editing?editing.assets.toFixed(2):''}/></label><label className="block space-y-1 text-sm"><span>Total liabilities ({currency})</span><Input name="liabilities" inputMode="decimal" required placeholder="0.00" defaultValue={editing?editing.liabilities.toFixed(2):''}/></label><p className="text-xs text-muted-foreground">Saving replaces any existing historical totals for this month. A manual current-month total stops automatic updates until you choose “Use live balances”.</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Saving…':'Save balance'}</Button></div></form></DialogContent></Dialog>
 </details>;
}
