"use client";
import { useLanguage } from "@/components/language-provider";

import { I18nText } from "@/components/language-provider";
import {useState,useEffect} from 'react';
import {ChevronDown,CalendarRange,RefreshCw} from 'lucide-react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {getAnnualBudget} from '@/lib/actions/annual-budget-actions';
import {buildAnnualBudget} from '@/lib/annual-budget';
import {albertaDate} from '@/lib/recurring-calendar';
import {formatMoney} from '@/lib/currency';
import {chartTooltipStyle,compactChartAmount} from '@/components/charts/financial-charts';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Report=ReturnType<typeof buildAnnualBudget> & {cardPayments?:{extraAssigned:number;paid:number}};
export function AnnualBudgetReport({currency}:{currency:string}){
 const { t: ppT } = useLanguage();

 const [open,setOpen]=useState(false),[year,setYear]=useState(albertaDate().slice(0,4)),[data,setData]=useState<Report|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const valid=/^\d{4}$/.test(year)&&Number(year)>=1900&&Number(year)<=9998;
 useEffect(()=>{if(!open)return;let active=true;setData(null);setError('');if(!valid){setLoading(false);return;}setLoading(true);getAnnualBudget(Number(year),currency).then(r=>{if(active){if(r.success&&r.data)setData(r.data);else setError(r.error||'Unable to load report.');}}).catch(()=>{if(active)setError('Unable to load report. Please retry.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[open,year,currency,refresh,valid]);
 useEffect(()=>{const focus=()=>{if(open)setRefresh(v=>v+1);};window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[open]);
 const money=(n:number)=>formatMoney(n,currency),monthLabel=(m:string)=>new Intl.DateTimeFormat('en',{month:'short',timeZone:'UTC'}).format(new Date(`${m}-01T12:00:00Z`));
 const period=data?.lastMonth===12?'Jan–Dec':data?.lastMonth?`Jan–${monthLabel(`${year}-${String(data.lastMonth).padStart(2,'0')}`)}`:'Future year';
 return <details className="group rounded-xl border bg-card text-card-foreground" onToggle={e=>setOpen(e.currentTarget.open)}>
  <summary className="flex cursor-pointer list-none items-center justify-between gap-3 rounded-xl px-4 py-3 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><CalendarRange aria-hidden className="h-4 w-4 text-teal-600 dark:text-teal-400"/>{""}<I18nText text={"Annual budget vs actual"}/>{""}</span><ChevronDown aria-hidden className="h-4 w-4 shrink-0 transition-transform group-open:rotate-180"/></summary>
  {open&&<div className="space-y-4 border-t p-4"><div className="flex flex-wrap items-end justify-between gap-3"><label className="block text-xs font-medium">{""}<I18nText text={"Report year"}/>{""}<Input className="mt-1 w-28" type="number" min="1900" max="9998" step="1" value={year} onChange={e=>setYear(e.target.value)}/></label><Button type="button" variant="outline" size="sm" disabled={loading||!valid} onClick={()=>setRefresh(v=>v+1)}><RefreshCw className="h-4 w-4"/>{""}<I18nText text={"Refresh report"}/>{""}</Button></div><p className="text-xs text-muted-foreground">{currency}{" "}<I18nText text={"only · independent of the time-range selector above"}/>{""}</p>
   {!valid?<p role="alert" className="text-sm">{""}<I18nText text={"Enter a year between 1900 and 9998."}/>{""}</p>:loading?<p role="status" className="text-sm text-muted-foreground">{""}<I18nText text={"Loading annual report…"}/>{""}</p>:error?<div role="alert" className="text-sm text-destructive"><I18nText text={error}/><Button variant="link" onClick={()=>setRefresh(v=>v+1)}>{""}<I18nText text={"Retry"}/>{""}</Button></div>:data&&<>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'Full-year plan',value:money(data.annualPlan),note:`${data.budgetMonths} of 12 months have budgets`},{label:`Plan · ${period}`,value:data.lastMonth?money(data.comparisonPlan):'—',note:'Includes the full current-month budget'},{label:`Spent · ${period}`,value:data.lastMonth?money(data.actual):'—',note:'Recorded expenses through today'},{label:'Budget remaining',value:data.comparedBudgetMonths?money(data.remaining):'—',note:data.comparedBudgetMonths?'Plan minus recorded spending':'No budget saved for this period'}].map((r,i)=><div key={r.label} className="min-w-0 rounded-lg border p-3"><p className="text-xs text-muted-foreground"><I18nText text={r.label}/></p><p className={`mt-1 break-words text-lg font-semibold tabular-nums ${i===3&&data.comparedBudgetMonths?(data.remaining<0?'text-red-600 dark:text-red-400':'text-teal-700 dark:text-teal-400'):''}`}>{r.value}</p><p className="mt-1 text-xs text-muted-foreground"><I18nText text={r.note}/></p></div>)}</div>
    {data.cardPayments && <section className="rounded-lg border p-3"><h3 className="text-sm font-semibold"><I18nText text="Credit card payment plan"/></h3><p className="mt-1 text-xs text-muted-foreground"><I18nText text="Shown separately from the category spending comparison. Repayments are transfers, not expenses."/></p><dl className="mt-2 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground"><I18nText text="Extra assigned · full year"/></dt><dd className="font-medium">{money(data.cardPayments.extraAssigned)}</dd></div><div><dt className="text-muted-foreground"><I18nText text="Payments through today"/></dt><dd className="font-medium">{money(data.cardPayments.paid)}</dd></div></dl></section>}
    <p className="text-xs leading-relaxed text-muted-foreground">{""}<I18nText text={"Only saved monthly budgets are included; no budget is copied or estimated."}/>{" "}{data.lastMonth>0&&data.comparedBudgetMonths<data.lastMonth?`${data.lastMonth-data.comparedBudgetMonths} month(s) in this comparison have no saved budget. `:''}{""}<I18nText text={"Transfers, savings transfers, and credit-card repayments are excluded from spending. Remaining budget is not a bank balance."}/>{""}</p>
    {data.budgetMonths===0&&data.actual===0?<p className="py-3 text-sm text-muted-foreground">{""}<I18nText text={"No budgets or recorded expenses for"}/>{" "}{year}{" "}<I18nText text={"in"}/>{" "}{currency}.</p>:<ResponsiveContainer width="100%" height={220}><BarChart data={data.months.map(r=>({...r,label:ppT(monthLabel(r.month)),planned:r.hasBudget?r.planned:null}))} margin={{top:12,right:8,left:0,bottom:0}}><CartesianGrid stroke="currentColor" opacity={0.1} vertical={false}/><XAxis dataKey="label" tick={{fill:'currentColor',fontSize:11}} minTickGap={12} tickLine={false} axisLine={false}/><YAxis width={48} tickFormatter={compactChartAmount} tick={{fill:'currentColor',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip formatter={v=>money(Number(v))} contentStyle={chartTooltipStyle}/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:12}}/><Bar dataKey="planned" name={ppT("Budget")} fill="#94a3b8" radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="actual" name={ppT("Recorded spending")} fill="#14b8a6" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer>}
    <details className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-sm font-medium">{""}<I18nText text={"Monthly details"}/>{""}</summary><div className="space-y-2 border-t p-3">{data.months.map(m=><div key={m.month} className="grid grid-cols-2 gap-2 rounded-lg border p-3 text-xs sm:grid-cols-4"><strong><I18nText text={monthLabel(m.month)}/> {year}{m.actual===null?<span className="ml-1 font-normal text-muted-foreground">{""}<I18nText text={"Planned"}/>{""}</span>:null}</strong><span>{""}<I18nText text={"Budget:"}/>{" "}<strong><I18nText text={m.hasBudget?money(m.planned):'Not set'}/></strong></span><span>{""}<I18nText text={"Spent:"}/>{" "}<strong>{m.actual===null?'—':money(m.actual)}</strong></span><span>{""}<I18nText text={"Remaining:"}/>{" "}<strong className={m.hasBudget&&m.actual!==null&&m.planned-m.actual<0?'text-red-600 dark:text-red-400':''}>{m.hasBudget&&m.actual!==null?money(m.planned-m.actual):'—'}</strong></span></div>)}</div></details>
    <div><h2 className="mb-2 text-sm font-semibold">{""}<I18nText text={"Category comparison ·"}/>{" "}{period}</h2><div className="space-y-2">{data.categories.length?data.categories.map(c=><div key={c.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-medium">{c.name}</h3><span className={`text-xs font-medium ${c.hasBudget&&c.remaining<0?'text-red-600 dark:text-red-400':'text-muted-foreground'}`}><I18nText text={c.hasBudget?`${money(c.remaining)} remaining`:'No budget set'}/></span></div><dl className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted-foreground">{""}<I18nText text={"Budget after reallocations"}/>{""}</dt><dd className="font-medium">{c.hasBudget?money(c.planned):'—'}</dd></div><div><dt className="text-muted-foreground">{""}<I18nText text={"Recorded spending"}/>{""}</dt><dd className="font-medium">{money(c.actual)}</dd></div></dl></div>):<p className="text-xs text-muted-foreground">{""}<I18nText text={"No categories to compare for this period."}/>{""}</p>}</div></div>
   </>}
  </div>}
 </details>;
}
