"use client";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, AreaChart, Area, ReferenceLine, Legend } from "recharts";
import { formatMoney } from "@/lib/currency";
import { statsDateLabel, type DateRange } from "@/lib/stats-date-range";
type Row = { month?: string; date?: string; name?: string; income?: number; expenses?: number; amount?: number; balance?: number; color?: string };
interface Props { currency?: string; type: "monthly-cashflow" | "category-spending" | "account-breakdown" | "daily-spend"; data: Row[]; dateRange: DateRange }
export function StatsCharts({ currency = "USD", type, data }: Props) {
  const money = (value: number) => formatMoney(value, currency);
  const compact = (value: number) => new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value);
  if (!data.length) return <p className="py-6 text-center text-sm text-muted-foreground">No data for this period.</p>;
  if (type === "category-spending") {
    const total = data.reduce((sum, row) => sum + Math.round((row.amount ?? 0) * 100), 0) / 100;
    return <div className="space-y-3"><p className="text-sm text-muted-foreground">Total expenses <span className="float-right font-semibold text-foreground">{money(total)}</span></p><div className="max-h-96 space-y-4 overflow-y-auto pr-1">{data.map((row, index) => {
      const share = total ? (row.amount ?? 0) / total * 100 : 0;
      return <div key={index} className="space-y-1.5"><div className="flex justify-between gap-3 text-sm"><span className="min-w-0 break-words">{row.name}</span><span className="shrink-0 font-medium tabular-nums">{money(row.amount ?? 0)}</span></div><div className="flex items-center gap-2"><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{ width: `${share}%`, backgroundColor: row.color }} /></div><span className="w-12 text-right text-xs text-muted-foreground">{share.toFixed(1)}%</span></div></div>;
    })}</div></div>;
  }
  if (type === "account-breakdown") {
    const rows = [...data].sort((a,b) => Math.abs(b.balance ?? 0) - Math.abs(a.balance ?? 0));
    return <div className="space-y-3"><div className="max-h-96 overflow-y-auto" role="img" aria-label="Current account balances, including negative balances"><ResponsiveContainer width="100%" height={Math.max(160, rows.length * 44)}><BarChart data={rows} layout="vertical" margin={{ right: 12, top: 8, bottom: 8 }}><CartesianGrid stroke="currentColor" opacity={0.1} horizontal={false} /><XAxis type="number" tickFormatter={compact} tick={{ fill: "currentColor", fontSize: 11 }} /><YAxis type="category" dataKey="name" width={110} tick={{ fill: "currentColor", fontSize: 11 }} tickFormatter={name => String(name).length > 17 ? String(name).slice(0,16)+"…" : String(name)} /><ReferenceLine x={0} stroke="currentColor" strokeOpacity={0.3} /><Tooltip formatter={value => money(Number(value))} contentStyle={{ background: "var(--background)", borderColor: "var(--border)", borderRadius: 12 }} /><Bar dataKey="balance" name="Balance" radius={4} isAnimationActive={false}>{rows.map((row,index) => <Cell key={index} fill={(row.balance ?? 0) < 0 ? "#ef4444" : row.color ?? "#14b8a6"} />)}</Bar></BarChart></ResponsiveContainer></div><div className="max-h-48 space-y-2 overflow-y-auto text-sm">{rows.map((row,index) => <div key={index} className="flex justify-between gap-3"><span>{row.name}</span><span className="shrink-0 font-medium tabular-nums">{money(row.balance ?? 0)}</span></div>)}</div><p className="text-xs text-muted-foreground">Current balances. Excludes debts tracked separately in Debts.</p></div>;
  }
  const monthly = type === "monthly-cashflow";
  const rows = data.map(row => ({ ...row, label: monthly ? statsDateLabel(row.month!, true) : row.date }));
  const axis = <><CartesianGrid stroke="currentColor" opacity={0.1} vertical={false} /><XAxis dataKey="label" minTickGap={25} tick={{ fill: "currentColor", fontSize: 11 }} tickFormatter={value => monthly ? value : statsDateLabel(value).replace(/,? \d{4}$/, "")} /><YAxis width={48} tickFormatter={compact} tick={{ fill: "currentColor", fontSize: 11 }} /><Tooltip formatter={value => money(Number(value))} labelFormatter={value => monthly ? value : statsDateLabel(String(value))} contentStyle={{ background: "var(--background)", borderColor: "var(--border)", borderRadius: 12 }} /></>;
  return <div role="img" aria-label={monthly ? "Income and expenses by month" : "Daily spending in the selected period"}><ResponsiveContainer width="100%" height={260}>{monthly ? <BarChart data={rows} margin={{ top: 12, right: 8 }}>{axis}<Legend /><Bar dataKey="income" name="Income" fill="#10b981" radius={[4,4,0,0]} isAnimationActive={false} /><Bar dataKey="expenses" name="Expenses" fill="#ef4444" radius={[4,4,0,0]} isAnimationActive={false} /></BarChart> : <AreaChart data={rows} margin={{ top: 12, right: 8 }}>{axis}<Area type="linear" dataKey="amount" name="Expenses" stroke="#f97316" fill="#f97316" fillOpacity={0.12} strokeWidth={2} isAnimationActive={false} /></AreaChart>}</ResponsiveContainer><p className="mt-2 text-xs text-muted-foreground">Amounts in {currency}. {monthly ? "Months without activity are shown as zero." : "Days without expenses are shown as zero."}</p></div>;
}
